BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path=public,extensions,pg_temp;
SELECT plan(23);
SELECT has_column('public','profile_systems','finish_authority','sourced finish chart is additive');
SELECT is((SELECT count(*)::INT FROM profile_systems WHERE version=5 AND is_global),6,'six additive v5 series');
SELECT is((SELECT count(*)::INT FROM profile_systems WHERE version<5 AND finish_authority IS NOT NULL),0,'historical chart stays absent');
SELECT ok((SELECT bool_and(finish_authority_valid(finish_authority,material::TEXT,finishes)) FROM profile_systems WHERE version=5),'all demo charts are valid');
SELECT ok((SELECT bool_and(finish_authority->'colors'->0->>'synthetic'='true') FROM profile_systems WHERE version=5),'DEMO is explicit');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.catalog_color_skus'::regclass),'color bindings preserve RLS');
SELECT ok(has_column_privilege('documentary_backend','public.profile_systems','finish_authority','SELECT'),'sealing role can read chart');
SELECT ok(has_table_privilege('pricing_backend','public.catalog_color_skus','SELECT'),'pricing role can read bindings');
SELECT ok((SELECT bool_and(stock_color=finish AND physical_stock_identity IS NOT NULL AND cutting_profile_id IS NOT NULL) FROM catalog_color_skus WHERE org_id IS NULL),'color-specific physical authorities are complete');
CREATE TEMP TABLE sample AS SELECT finish_authority AS a,material::TEXT AS m,finishes AS f FROM profile_systems WHERE code='DEMO_60' AND version=5;
SELECT ok((SELECT NOT finish_authority_valid(a||'{"source":""}',m,f) FROM sample),'empty chart source rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{colors,0,linear_rgb,0}','"1.00001"'),m,f) FROM sample),'out of range linear channel rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{colors,0,linear_rgb,0}','0.1'),m,f) FROM sample),'binary-float transport rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{colors,0,gloss}','"-0.1"'),m,f) FROM sample),'negative gloss rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{colors,0,texture_path}','"/catalog-assets/../secret"'),m,f) FROM sample),'texture traversal rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,base}','"CREAM"'),m,f) FROM sample),'base and mass face must agree');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,exterior}','"ABSENT"'),m,f) FROM sample),'unknown exterior rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,surcharge,amount}','"0.001"'),m,f) FROM sample),'NONE surcharge must declare zero');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,max_leaf_width_mm}','"0"'),m,f) FROM sample),'zero leaf limit rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,extra_lead_days}','-1'),m,f) FROM sample),'negative extra lead time rejected');
SELECT ok((SELECT NOT finish_authority_valid(jsonb_set(a,'{combinations,0,allowed_handle_colors}','["ABSENT"]'),m,f) FROM sample),'missing handle sample rejected');
SELECT ok((SELECT NOT finish_authority_valid(a,m,'["WHITE"]') FROM sample),'stock identities and combinations must agree');
SELECT ok((SELECT NOT finish_authority_valid(a,'ALUMINIUM',f) FROM sample),'wrong material rejected');
SELECT is((SELECT count(*)::INT FROM profile_systems s WHERE version=5 AND (SELECT count(*) FROM inspector_rule_configs r WHERE r.system_id=s.id AND r.is_active)=14),6,'every v5 series has seeded inspection authority');
SELECT * FROM finish();
ROLLBACK;
