BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path=public,extensions,pg_temp;
SELECT plan(23);
SELECT has_table('public','mounting_rules','sourced rules exist');
SELECT has_table('public','position_measurements','revision-bound evidence exists');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.mounting_rules'::regclass),'rules have RLS');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.position_measurements'::regclass),'evidence has RLS');
SELECT ok(NOT has_table_privilege('authenticated','public.mounting_rules','SELECT'),'raw rule access denied');
SELECT ok(NOT has_table_privilege('authenticated','public.mounting_rules','INSERT'),'raw rule write denied');
SELECT ok(NOT has_table_privilege('authenticated','public.position_measurements','SELECT'),'raw survey access denied');
SELECT ok(NOT has_table_privilege('authenticated','public.position_measurements','INSERT'),'confirmation cannot bypass backend');
SELECT ok(has_table_privilege('pricing_backend','public.mounting_rules','SELECT,INSERT'),'trusted rules boundary');
SELECT ok(has_table_privilege('pricing_backend','public.position_measurements','SELECT,INSERT'),'trusted evidence boundary');
SELECT ok(has_table_privilege('documentary_backend','public.position_measurements','SELECT'),'seal reads evidence');
SELECT ok(NOT has_table_privilege('documentary_backend','public.position_measurements','INSERT'),'seal cannot fabricate confirmation');
SELECT ok(NOT has_table_privilege('pricing_backend','public.mounting_rules','UPDATE,DELETE'),'rule history cannot be rewritten');
SELECT ok(NOT has_table_privilege('pricing_backend','public.position_measurements','UPDATE,DELETE'),'survey history cannot be rewritten');
SELECT has_trigger('public','mounting_rules','mounting_rules_immutable','rules remain immutable for elevated writers');
SELECT has_trigger('public','position_measurements','position_measurements_immutable','evidence remains immutable for elevated writers');
SELECT has_trigger('public','mounting_rules','mounting_rule_contract','actor, identity, source and exact allowances guarded');
SELECT has_trigger('public','position_measurements','position_measurement_revision','actor, active revision and generation guarded');
SELECT has_trigger('public','orders','workshop_measurements_gate','raw OT inserts enforce confirmation');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid='private.guard_position_measurement()'::regprocedure),'narrow seal lookup does not broaden pricing grants');
SELECT ok(NOT has_function_privilege('authenticated','private.lock_measurement_target(uuid,uuid)','EXECUTE'),'member cannot call privileged locks');
SELECT ok(has_function_privilege('pricing_backend','private.lock_measurement_target(uuid,uuid)','EXECUTE'),'trusted confirmation can lock');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid='private.lock_measurement_target(uuid,uuid)'::regprocedure),'narrow lock does not grant general project edits');
SELECT * FROM finish();
ROLLBACK;
