BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path=public,extensions,pg_temp;
SELECT plan(13);
SELECT has_column('public','tenancy_organizations','document_preferences','organization preferences exist');
SELECT has_column('public','project_documentary_inputs','commercial_terms','terms are structured declarations');
SELECT has_column('public','project_documentary_inputs','alternative_version_ids','alternative authority is explicit');
SELECT has_table('public','document_portal_links','PDF has its own immutable capability');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.document_portal_links'::regclass),'capability has RLS');
SELECT ok(NOT has_table_privilege('anon','public.document_portal_links','SELECT'),'anonymous cannot read ciphertext');
SELECT ok(NOT has_table_privilege('authenticated','public.document_portal_links','SELECT'),'members cannot query ciphertext');
SELECT ok(NOT has_table_privilege('portal_backend','public.document_portal_links','SELECT'),'public portal cannot query ciphertext');
SELECT ok(has_table_privilege('documentary_backend','public.document_portal_links','SELECT,INSERT'),'document generator can create private capability');
SELECT ok(NOT has_table_privilege('documentary_backend','public.document_portal_links','UPDATE,DELETE'),'generator cannot rewrite or delete capability');
SELECT has_trigger('public','document_portal_links','document_portal_link_authority','capability authority guarded');
SELECT has_trigger('public','customer_approvals','document_approval_identity','printed QR binding guarded');
SELECT has_trigger('public','project_documentary_inputs','quote_alternative_scope','alternative tenant and project are guarded');
SELECT * FROM finish();
ROLLBACK;
