BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path=public,extensions,pg_temp;
SELECT plan(14);
SELECT has_column('public','pricing_rules','minimum_margin_pct','minimum is declared');
SELECT has_column('public','pricing_rules','maximum_margin_pct','maximum is declared');
SELECT has_column('public','pricing_rules','discount_approval_pct','discount threshold is declared');
SELECT col_type_is('public','pricing_rules','minimum_margin_pct','numeric(6,4)','minimum is exact');
SELECT has_check('public','pricing_rules','band has a database constraint');
SELECT has_trigger('public','pricing_rules','p07_rules_lock','rules serialize with estimator apply');
SELECT has_table('public','pricing_attention_receipts','decisions have explicit receipts');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.pricing_attention_receipts'::regclass),'receipts keep tenant RLS');
SELECT ok(NOT has_table_privilege('anon','public.pricing_attention_receipts','SELECT'),'anonymous cannot read receipt');
SELECT ok(NOT has_table_privilege('authenticated','public.pricing_attention_receipts','SELECT'),'client cannot directly read receipt');
SELECT ok(has_table_privilege('pricing_backend','public.pricing_attention_receipts','SELECT,INSERT'),'calculator can receive acknowledgment');
SELECT ok(NOT has_table_privilege('pricing_backend','public.pricing_attention_receipts','UPDATE'),'receipts cannot be rewritten');
SELECT ok(NOT has_table_privilege('pricing_backend','public.pricing_attention_receipts','DELETE'),'receipts cannot be erased');
SELECT col_is_pk('public','pricing_attention_receipts',ARRAY['org_id','operation_id','user_id'],'receipt is idempotent per tenant, operation and person');
SELECT * FROM finish();
ROLLBACK;
