BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path=public,private,auth,extensions,pg_temp;
SELECT plan(13);
SELECT has_column('public','profile_articles','coupling_rule','joint authority is catalog data');
SELECT ok(coupling_rule_valid(NULL,'COUPLER'),'absence preserves historical joints');
SELECT ok(coupling_rule_valid('{"min_angle_deg":"0","max_angle_deg":"60","development_mm":"0","source":"Ficha A"}','COUPLER'),'shared pivot is explicitly valid');
SELECT ok(coupling_rule_valid('{"min_angle_deg":"90","max_angle_deg":"90","development_mm":"24.00","source":"Ficha B"}','COUPLER'),'exact corner and additive width are valid');
SELECT ok(NOT coupling_rule_valid('{"min_angle_deg":"30","max_angle_deg":"15","development_mm":"0","source":"Ficha"}','COUPLER'),'reversed limits rejected');
SELECT ok(NOT coupling_rule_valid('{"min_angle_deg":"0","max_angle_deg":"60","development_mm":"-1","source":"Ficha"}','COUPLER'),'negative contribution rejected');
SELECT ok(NOT coupling_rule_valid('{"min_angle_deg":"0","max_angle_deg":"91","development_mm":"0","source":"Ficha"}','COUPLER'),'range is limited to ninety degrees');
SELECT ok(NOT coupling_rule_valid('{"min_angle_deg":"0","max_angle_deg":"60","development_mm":"0","source":" "}','COUPLER'),'blank source rejected');
SELECT ok(NOT coupling_rule_valid('{"min_angle_deg":"0","max_angle_deg":"60","development_mm":"0","source":"Ficha"}','FRAME'),'authority cannot leak to a frame role');
SELECT ok(has_column_privilege('authenticated','profile_articles','coupling_rule','SELECT'),'tenant readers can read only through existing RLS');
SELECT is((SELECT count(*)::INT FROM profile_articles a JOIN profile_systems s ON s.id=a.system_id WHERE s.version=7 AND s.is_demo AND a.coupling_rule IS NOT NULL),12,'six additive DEMO series carry two sourced joints');
SELECT is((SELECT count(*)::INT FROM profile_articles a JOIN profile_systems s ON s.id=a.system_id WHERE s.version<7 AND a.coupling_rule IS NOT NULL),0,'previous DEMO versions remain byte-compatible');
SELECT ok((SELECT bool_and(coupling_rule_valid(a.coupling_rule,a.role::TEXT)) FROM profile_articles a JOIN profile_systems s ON s.id=a.system_id WHERE s.version=7 AND s.is_demo),'all synthetic rules validate');
SELECT * FROM finish();
ROLLBACK;
