BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path=public,extensions;
SELECT plan(16);
SELECT col_type_is('public','project_payments','amount','numeric(14,2)','Ledger amounts remain exact');
SELECT has_column('public','project_payments','actor_label','Actor evidence survives identity changes');
SELECT has_column('public','project_payments','simulated','Simulated payments cannot impersonate actual cash');
SELECT has_trigger('public','project_payments','collection_payment_actor','Actor derives from trusted claims');
SELECT has_trigger('public','project_payment_links','collection_link_identity','Link identity and expiry are sealed');
SELECT col_type_is('public','project_payment_links','expires_at','timestamp with time zone','Expiry is timezone aware');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.collection_preferences'::regclass),'Collection preferences carry RLS');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.project_fiscal_simulations'::regclass),'Fiscal simulation evidence carries RLS');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.collection_reminders'::regclass),'AI reminders carry RLS');
SELECT ok(NOT has_table_privilege('anon','public.project_fiscal_simulations','SELECT'),'Anonymous cannot list simulated documents');
SELECT ok(NOT has_table_privilege('authenticated','public.collection_preferences','UPDATE'),'Members cannot alter integrations directly');
SELECT ok(NOT has_table_privilege('documentary_backend','public.project_fiscal_simulations','UPDATE'),'Backend cannot rewrite simulation history');
SELECT ok(NOT has_table_privilege('documentary_backend','public.collection_reminders','DELETE'),'Backend cannot erase AI reminder evidence');
SELECT has_trigger('public','project_fiscal_simulations','fiscal_simulation_immutable','Fiscal evidence is append only even for privileged users');
SELECT has_trigger('public','collection_reminders','collection_reminders_immutable','AI letter evidence is immutable');
SELECT ok(NOT has_function_privilege('anon','private.collection_payment_actor()','EXECUTE'),'Actor function cannot be invoked anonymously');
SELECT * FROM finish();
ROLLBACK;
