BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SET LOCAL search_path = public,private,auth,extensions,pg_temp;
SELECT plan(14);
SELECT has_table('public','cnc_authority_events','Append-only CNC authority history');
SELECT has_column('public','cnc_machines','axes','Declared machine axes');
SELECT has_column('public','cnc_machines','clamps_declared','Explicit clamp review');
SELECT has_column('public','cnc_machines','machine_type','Machine type is explicit');
SELECT has_column('public','cnc_machines','profile_setups','Physical loading setup distinct from drawing');
SELECT has_column('public','cnc_programs','review_fingerprint','Generation binds explicit review');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='cnc_authority_events'::regclass),'History has RLS');
SELECT ok(NOT has_table_privilege('authenticated','cnc_authority_events','INSERT'),'History cannot be fabricated by callers');
SELECT ok(NOT has_table_privilege('service_role','cnc_authority_events','UPDATE'),'History service cannot rewrite rows');
SELECT ok(NOT has_table_privilege('documentary_backend','cnc_machines','DELETE'),'Machines retire rather than disappear');
SELECT ok(NOT has_table_privilege('documentary_backend','cnc_tools','DELETE'),'Tools retire rather than disappear');
SELECT has_trigger('public','cnc_programs','cnc_program_evidence_guard','Program contents stay immutable');
SELECT has_trigger('public','cnc_tools','cnc_tool_authority_guard','Role and tenant enforced at storage boundary');
SELECT has_trigger('public','cnc_machines','cnc_machine_authority_trace','Machine declarations are audited');
SELECT * FROM finish();
ROLLBACK;
