BEGIN;
SELECT plan(15);
SELECT has_column('public','order_receipts','supplier_document','Supplier guide is retained');
SELECT col_type_is('public','order_receipts','received_on','date','Physical reception has an explicit date');
SELECT col_type_is('public','inventory_remnants','physical_stock_identity','text','D05 stock identities retain their exact text');
SELECT has_trigger('public','order_requirement_lines','purchase_quantity_capacity','Partial purchases serialize physical capacity');
SELECT ok((SELECT prosecdef FROM pg_proc WHERE oid='private.purchase_quantity_capacity()'::regprocedure),'Capacity lock uses a bounded definer');
SELECT ok(NOT has_function_privilege('anon','private.purchase_quantity_capacity()','EXECUTE'),'Anonymous cannot invoke purchase capacity');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.purchase_need_decisions'::regclass),'Purchase decisions carry RLS');
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.inventory_remnant_events'::regclass),'Physical remnant history carries RLS');
SELECT ok(NOT has_table_privilege('authenticated','public.purchase_need_decisions','SELECT'),'Purchase decisions have no direct member read');
SELECT ok(NOT has_table_privilege('authenticated','public.inventory_remnant_events','INSERT'),'Physical history is written by the validated service');
SELECT ok(NOT has_table_privilege('documentary_backend','public.inventory_remnant_events','UPDATE'),'Physical history cannot be edited by the service');
SELECT has_trigger('public','inventory_remnant_events','inventory_history_immutable','Even privileged remnant history is immutable');
SELECT has_trigger('public','purchase_need_decisions','purchase_decision_immutable','Human purchase decisions are immutable');
SELECT has_trigger('public','inventory_remnants','trace_remnant_change','Each physical transition retains its actor and rack');
SELECT has_trigger('public','inventory_movements','inventory_movement_actor','Production movements inherit the verified actor');
SELECT * FROM finish();
ROLLBACK;
