"""Outline the self-hosted Plex wordmark; no font/network dependency in SVG.

Run with the development Python environment. PNG app icons are rasterized from
these SVGs by frontend/scripts/build-brand-icons.mjs in Chromium.
"""

from __future__ import annotations

import json
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "frontend/src/brand"
PUBLIC = ROOT / "frontend/public"
RING = "M2 0H22Q24 0 24 2V22Q24 24 22 24H2Q0 24 0 22V2Q0 0 2 0ZM2.5 2.5V21.5H21.5V2.5Z"
OPTICAL_RING = "M2 0H22Q24 0 24 2V22Q24 24 22 24H2Q0 24 0 22V2Q0 0 2 0ZM3 3V21H21V3Z"


def main() -> None:
    BRAND.mkdir(exist_ok=True)
    font = TTFont(PUBLIC / "fonts/ibm-plex-sans-latin-600-normal.woff2")
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = 24 / font["OS/2"].sCapHeight
    tracking = font["head"].unitsPerEm * 0.06 * scale
    x = 0.0
    paths = []
    for letter in "DEKOPEN":
        if letter == "O":
            mark_x = round(x, 4)
            x += 24 + tracking
            continue
        glyph = glyphs[cmap[ord(letter)]]
        pen = SVGPathPen(glyphs)
        glyph.draw(pen)
        paths.append({"d": pen.getCommands(), "x": round(x, 4)})
        x += glyph.width * scale + tracking
    width = round(x - tracking, 4)
    data = {"paths": paths, "scale": round(scale, 8), "markX": mark_x, "width": width}
    (BRAND / "wordmarkGeometry.ts").write_text(
        "// Generated by scripts/build_brand_assets.py from bundled IBM Plex Sans 600.\n"
        + "export const wordmarkGeometry = "
        + json.dumps(data, ensure_ascii=False)
        + " as const;\n",
        encoding="utf-8",
    )
    mark = f'<path fill-rule="evenodd" d="{RING}"/><path d="M7 2.5H9V21.5H7Z"/>'
    outlined = (
        "".join(
            f'<path transform="translate({item["x"]} 24) scale({scale:.8f} {-scale:.8f})" '
            f'd="{item["d"]}"/>'
            for item in paths
        )
        + f'<g transform="translate({mark_x} 0)">{mark}</g>'
    )
    for name, geometry, vw, vh in (
        ("brandmark", mark, 24, 24),
        ("wordmark", outlined, width, 24),
        (
            "doc-lockup",
            f'<g transform="translate(4 4)">{outlined}</g>'
            f'<path fill="none" stroke="currentColor" stroke-width="0.75" '
            f'd="M4 32V40M{width + 4} 32V40M4 36H{width + 4}'
            f'M1 39L7 33M{width + 1} 39L{width + 7} 33"/>',
            width + 8,
            44,
        ),
    ):
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vw} {vh}" fill="currentColor" aria-label="DEKOPEN">{geometry}</svg>\n'
        (BRAND / f"{name}.svg").write_text(svg, encoding="utf-8")
    # Optical correction is limited to the favicon/mark below 24 px.
    small = f'<path fill-rule="evenodd" d="{OPTICAL_RING}"/><path d="M6.875 3H9.125V21H6.875Z"/>'
    for theme, ink, paper in (("light", "#075f5a", "#ffffff"), ("dark", "#fcfdfc", "#161c1f")):
        (PUBLIC / f"favicon-{theme}.svg").write_text(
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">'
            f'<rect width="24" height="24" fill="{paper}"/>'
            f'<g fill="{ink}">{small}</g></svg>\n',
            encoding="utf-8",
        )
    (PUBLIC / "favicon.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">'
        "<style>.paper{fill:#fff}.section{fill:#075f5a}"
        "@media(prefers-color-scheme:dark){.paper{fill:#161c1f}.section{fill:#fcfdfc}}</style>"
        f'<rect class="paper" width="24" height="24"/><g class="section">{small}</g></svg>\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
