"""Reproduce D05's exact contract and additive v5 finish authorities."""

import json
from pathlib import Path
import sys
from uuid import NAMESPACE_URL, uuid5

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "engine/src"))
from backend.catalogs.demo_finishes import finish_manifest, SOURCE  # noqa: E402
from dekopen_engine.finish_models import FinishAuthority  # noqa: E402
from scripts.generate_demo_catalog import insert, uid  # noqa: E402
from scripts.generate_demo_hardware import hardware_sql, documentary_seed_sql  # noqa: E402

SCHEMA_FILE = ROOT / "supabase/migrations/20270102000000_finish_authority.sql"
DEMO_FILE = ROOT / "supabase/migrations/20270102000100_demo_finish_catalog.sql"
SEED_MARKER = "-- D05 generated documentary seed; see scripts/generate_demo_finishes.py."


def schema_sql() -> str:
    schema = json.dumps(FinishAuthority.model_json_schema(), ensure_ascii=False, sort_keys=True)
    assert "prefixItems" not in schema
    return ("-- Generated by scripts/generate_demo_finishes.py. Additive, exact, PostgreSQL 16/17.\nBEGIN;\n"
        + (ROOT / "scripts/finish_schema.sql").read_text(encoding="utf-8").replace("__SCHEMA__", schema.replace("'", "''"))
        + "\nCOMMIT;\n")


def finish_sql() -> str:
    records = finish_manifest()
    sql = hardware_sql(records, version=5).removesuffix("COMMIT;\n")
    sql = sql.replace("scripts/generate_demo_hardware.py", "scripts/generate_demo_finishes.py")
    statements = []
    saw = str(uuid5(NAMESPACE_URL, "https://dekopen.local/shot07/cutting/DEMO"))
    for record in records:
        code = record["code"]
        authority = FinishAuthority.model_validate_json(json.dumps(record["params"]["finish_authority"]))
        system = uid(code, version=5)
        # generated_sql inserts the chart's combination codes; add authority
        # before any position can reference this new, never-before-issued row.
        payload = json.dumps(authority.model_dump(mode="json"), ensure_ascii=False).replace("'", "''")
        statements.append(f"UPDATE public.profile_systems SET finish_authority='{payload}'::JSONB WHERE id='{system}';")
        for binding in record["finish_bindings"]:
            sku, finish = binding["sku"], binding["finish"]
            statements.append(insert("catalog_color_skus", {"id": uid(code, "finish/"+sku+"/"+finish, version=5),
                "org_id": None, "system_id": system, "profile_article_id": uid(code, sku, version=5),
                "finish": finish, "commercial_sku": binding["commercial_sku"],
                "physical_stock_identity": uid(code, "stock/"+sku+"/"+finish, version=5),
                "source": SOURCE, "manufacturer_name": "Fabricante sintético · DEMO",
                "supplier_name": "Proveedor sintético", "stock_color": finish,
                "cutting_profile_id": saw, "binding_version": 1, "purchase_unit": "BAR", "is_active": True}))
    return sql+"\n"+"\n".join(statements)+"\nCOMMIT;\n"


def finish_seed_sql() -> str:
    # Same source policies, separate identities. Historical seed remains intact.
    return documentary_seed_sql().replace("-- D04 generated documentary seed; see scripts/generate_demo_hardware.py.", SEED_MARKER).replace(
        "d04_seed", "d05_seed").replace("catalog/v4/", "catalog/v5/").replace("s.version=4", "s.version=5").replace("_DEMO_V4", "_DEMO_V5")


if __name__ == "__main__":
    SCHEMA_FILE.write_text(schema_sql(), encoding="utf-8", newline="\n")
    DEMO_FILE.write_text(finish_sql(), encoding="utf-8", newline="\n")
    seed = ROOT / "supabase/seed.sql"
    prior = seed.read_text(encoding="utf-8").split(SEED_MARKER, 1)[0].rstrip()
    seed.write_text(prior+"\n\n"+finish_seed_sql(), encoding="utf-8", newline="\n")
    print("D05 schema and additive v5 finish charts reproduced.")
