"""Reproduce D01's synthetic seed; never run against an existing database."""

from pathlib import Path
from decimal import Decimal
import json
import sys
from uuid import NAMESPACE_URL, uuid5

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from backend.catalogs.demo_fixture import manifest  # noqa: E402

MIGRATION = ROOT / "supabase/migrations/20261229000200_catalog_demo_family_seed.sql"


def uid(code, key="system"):
    return str(uuid5(NAMESPACE_URL, f"https://dekopen.local/catalog/v2/{code}/{key}"))


def literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (dict, list)):
        return "'" + native_json(value).replace("'", "''") + "'::JSONB"
    return "'" + str(value).replace("'", "''") + "'"


def native_json(value):
    if isinstance(value, dict):
        return "{" + ",".join(json.dumps(key) + ":" + native_json(item)
                              for key, item in sorted(value.items())) + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(native_json(item) for item in value) + "]"
    if isinstance(value, Decimal):
        if not value.is_finite():
            raise ValueError("Non-finite catalog authority")
        return format(value, "f")
    if isinstance(value, float):
        raise TypeError("Catalog authorities require exact decimals")
    return json.dumps(value, ensure_ascii=False, allow_nan=False)


def insert(table, values):
    return (f"INSERT INTO public.{table} ({','.join(values)}) VALUES\n"
            f"({','.join(literal(value) for value in values.values())}) ON CONFLICT (id) DO NOTHING;\n")


def generated_sql():
    records = manifest()
    sql = ["-- Generated by scripts/generate_demo_catalog.py. Synthetic, deterministic, uncertified.\nBEGIN;\n"]
    for record in records:
        code, params = record["code"], record["params"]
        system_id = uid(code)
        scalar = {key: params[key] for key in (
            "depth_mm", "material", "sash_overlap_mm", "glass_clearance_white_mm", "glass_clearance_foil_mm",
            "rebate_depth_mm", "end_milling_overlap_mm", "corner_bracket_loss_mm", "hook_depth_mm",
            "door_threshold_mm", "door_bottom_clearance_mm", "door_leaf_side_clearance_mm", "finishes", "dimensional_limits")}
        sql.append(insert("profile_systems", {"id": system_id, "org_id": None, "code": code,
            "name": record["name"], "system_family": params["system_family"], "sliding_parameters": params["sliding"],
            "version": 2, "is_global": True, "is_demo": True, "legacy_authority": False,
            "chamber_count": 3 if params["material"] == "PVC" else 1,
            "chamber_clearance_mm": "12.00", "data_provenance": "SEED_SYNTHETIC", **scalar}))
        for article in record["articles"]:
            sku = article["sku"]
            section = {"source": "POLYGON", "depth_mm": Decimal(params["depth_mm"]),
                "orientation": "EXTERIOR_DOWN", "local_origin": "TOP_LEFT",
                "polygon": [{"x_mm": Decimal("0.00"), "y_mm": Decimal("0.00")},
                    {"x_mm": Decimal(article["face_width_mm"]), "y_mm": Decimal("0.00")},
                    {"x_mm": Decimal(article["face_width_mm"]), "y_mm": Decimal(params["depth_mm"])},
                    {"x_mm": Decimal("0.00"), "y_mm": Decimal(params["depth_mm"])}]}
            sql.append(insert("profile_articles", {"id": uid(code, sku), "org_id": None,
                "system_id": system_id, "data_provenance": "SEED_SYNTHETIC", "section": section, **article}))
            sql.append(insert("profile_purchase_mappings", {"id": uid(code, "purchase/" + sku),
                "org_id": None, "profile_article_id": uid(code, sku), "commercial_sku": "COMPRA-" + sku,
                "manufacturer_name": "Catálogo DEMO", "supplier_name": "Proveedor sintético",
                "purchase_unit": "BAR", "physical_stock_identity": uid(code, "stock/" + sku),
                "stock_color": "WHITE", "binding_version": 1,
                "cutting_profile_id": str(uuid5(NAMESPACE_URL, "https://dekopen.local/shot07/cutting/DEMO"))}))
            if article["reinforcement_rule"]:
                steel = article["reinforcement_sku"]
                sql.append(insert("reinforcement_articles", {"id": uid(code, steel), "org_id": None,
                    "system_id": system_id, "parent_profile_article_id": uid(code, sku), "sku": steel,
                    "commercial_sku": "COMPRA-" + steel, "name": "Refuerzo DEMO", "manufacturer_name": "Catálogo DEMO",
                    "supplier_name": "Proveedor sintético", "stock_length_mm": "6000.00", "purchase_unit": "BAR",
                    "is_default": True, "physical_stock_identity": uid(code, "stock/" + steel), "stock_color": "WHITE",
                    "binding_version": 1,
                    "cutting_profile_id": str(uuid5(NAMESPACE_URL, "https://dekopen.local/shot07/cutting/DEMO"))}))
        for thickness, bead in params["glazing_bead_rules"].items():
            sql.append(insert("glazing_bead_matrix", {"id": uid(code, "bead/" + thickness), "org_id": None,
                "system_id": system_id, "bead_article_id": uid(code, bead["bead_article"]["sku"]),
                "data_provenance": "SEED_SYNTHETIC", **{key: value for key, value in bead.items() if key != "bead_article"}}))
        for kit in params["available_hardware_kits"]:
            values = {**kit, "contents": [{**component, "qty": int(component["qty"])} for component in kit["contents"]]}
            sql.append(insert("hardware_kits", {"id": uid(code, kit["sku"]), "org_id": None,
                "system_id": system_id, "data_provenance": "SEED_SYNTHETIC", **values}))
            sql.append(insert("hardware_purchase_mappings", {"id": uid(code, "purchase/" + kit["sku"]), "org_id": None,
                "hardware_kit_id": uid(code, kit["sku"]), "purchasing_sku": "COMPRA-" + kit["sku"],
                "manufacturer_name": "Catálogo DEMO", "purchase_unit": "KIT", "version": 1,
                "provenance": {"mode": "KIT_ONLY", "source": record["source"]}}))
        for glass in record["glasses"]:
            sql.append(insert("glass_purchase_mappings", {"id": uid(code, glass["sku"]), "org_id": None,
                "system_id": system_id, "technical_sku": glass["sku"], "glass_spec": glass["glass_spec"],
                "purchasing_sku": "COMPRA-" + glass["sku"], "manufacturer_name": "Catálogo DEMO",
                "purchase_unit": "EA", "version": 1,
                "provenance": {"source": record["source"], "certified": "false"}}))
        for price in record["prices"]:
            sql.append(insert("catalog_demo_prices", {"id": uid(code, "price/" + price["sku"]), "org_id": None,
                "system_id": system_id, "seed": record["seed"], "source": record["source"], "is_demo": True,
                "currency": "CLP", **price}))
        if params["material"] == "PVC":
            screw = code + "-TORNILLO-REF"
            sql.append(insert("fitting_purchase_mappings", {"id": uid(code, screw), "org_id": None,
                "system_id": system_id, "technical_sku": screw, "purchasing_sku": "COMPRA-" + screw,
                "manufacturer_name": "Catálogo DEMO", "purchase_unit": "EA", "version": 1,
                "provenance": {"source": record["source"], "certified": "false"}}))
        sql.append(f"""
INSERT INTO public.inspector_rule_configs(id,system_id,org_id,rule_id,params)
SELECT uuid_generate_v5(uuid_ns_url(), 'https://dekopen.local/catalog/v2/{code}/inspection/'||rule_id),
    '{system_id}',NULL,rule_id,params FROM public.inspector_rule_configs
WHERE system_id='3067da09-3119-5ad0-a1d5-498cd2dfd753' AND org_id IS NULL
ON CONFLICT (id) DO NOTHING;
""")
        for table in ("manufacturing_placement_policies", "handle_requirement_policies"):
            sql.append(f"""
INSERT INTO public.{table}(id,system_id,org_id,version,authority)
SELECT '{uid(code, table)}','{system_id}',NULL,version,
    jsonb_set(authority,'{{policy_id}}',to_jsonb('{code}_DEMO_V2'::TEXT))
FROM public.{table} WHERE system_id='3067da09-3119-5ad0-a1d5-498cd2dfd753' AND org_id IS NULL
ORDER BY version DESC,id LIMIT 1 ON CONFLICT (id) DO NOTHING;
""")
        rules = []
        for article in record["articles"]:
            if article["reinforcement_rule"]:
                angle = article["cut_rule"]["angle_degrees"]
                rules.append({"role": article["role"], "profile_angle_left": angle, "profile_angle_right": angle,
                    "reinforcement_angle_left": 90, "reinforcement_angle_right": 90,
                    "length_authority": "EXISTING_ENGINE", "compatible_with_existing_length": True})
        if not rules:
            rules = [{"role": "FRAME", "profile_angle_left": 45, "profile_angle_right": 45,
                "reinforcement_angle_left": 90, "reinforcement_angle_right": 90,
                "length_authority": "EXISTING_ENGINE", "compatible_with_existing_length": True}]
        if rules:
            sql.append(insert("reinforcement_cut_policies", {"id": uid(code, "reinforcement_cut_policies"),
                "system_id": system_id, "org_id": None, "version": 2,
                "authority": {"schema_version": 1, "policy_id": code + "_REFUERZO_DEMO_V2", "version": 2, "rules": rules}}))
    sql.append("COMMIT;\n")
    # Resolve the canonical existing saw identity without inventing a second default.
    return "\n".join(sql)


if __name__ == "__main__":
    MIGRATION.write_text(generated_sql(), encoding="utf-8", newline="\n")
    print("D01 deterministic demo migration regenerated; seed 20261005.")
