"""Reproduce D04 schema validation and additive synthetic v4 catalog."""

from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "engine/src"))
from dekopen_engine.models import HardwareClassAuthority  # noqa: E402
from backend.catalogs.demo_hardware import hardware_manifest  # noqa: E402
from backend.catalogs.demo_glass import demo_glass_product, demo_glass_rates, SOURCE  # noqa: E402
from scripts.generate_demo_catalog import generated_sql, insert, uid, shared_demo_price  # noqa: E402


def schema_sql() -> str:
    schema = json.dumps(HardwareClassAuthority.model_json_schema(), ensure_ascii=False, sort_keys=True)
    supported = {"$defs", "$ref", "additionalProperties", "properties", "required", "type", "title", "description",
        "anyOf", "const", "enum", "default", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum",
        "minLength", "maxLength", "minItems", "maxItems", "pattern", "items"}
    def check(value):
        if isinstance(value, dict):
            assert not set(value)-supported, f"Unsupported hardware schema keywords: {set(value)-supported}"
            for key,child in value.items():
                if key in ("$defs", "properties"):
                    for node in child.values():
                        check(node)
                elif key not in ("default", "enum", "const", "required"):
                    check(child)
        elif isinstance(value, list):
            for child in value:
                check(child)
    check(json.loads(schema))
    return """-- Generated by scripts/generate_demo_hardware.py from the typed engine contract.
BEGIN;
__SCHEMA_VALIDATOR__
ALTER TABLE public.hardware_kits ADD COLUMN class_authority JSONB;
GRANT SELECT(class_authority) ON public.hardware_kits TO authenticated, catalog_backend, pricing_backend, documentary_backend;

CREATE FUNCTION public.hardware_component_rule_valid(c JSONB) RETURNS BOOLEAN
LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public AS $$
DECLARE m JSONB;
BEGIN
  IF (c->'quantity'->>'base')::NUMERIC < 0 THEN RETURN FALSE; END IF;
  IF c->'quantity'->>'axis' IS NULL THEN
    IF c->'quantity'->>'threshold' IS NOT NULL OR c->'quantity'->>'step' IS NOT NULL THEN RETURN FALSE; END IF;
  ELSE
    IF c->'quantity'->>'threshold' IS NULL OR c->'quantity'->>'step' IS NULL
       OR (c->'quantity'->>'threshold')::NUMERIC < 0 OR (c->'quantity'->>'step')::NUMERIC <= 0 THEN RETURN FALSE; END IF;
  END IF;
  IF c->>'weight_kg' IS NOT NULL AND c->>'weight_kg_m' IS NOT NULL THEN RETURN FALSE; END IF;
  IF COALESCE((c->>'weight_kg')::NUMERIC,0) < 0 OR COALESCE((c->>'weight_kg_m')::NUMERIC,0) < 0 THEN RETURN FALSE; END IF;
  IF (c->>'price_unit'='M' OR c->>'weight_kg_m' IS NOT NULL) AND (c->'length' IS NULL OR c->'length'='null'::JSONB) THEN RETURN FALSE; END IF;
  IF c->'length' IS NOT NULL AND c->'length'<>'null'::JSONB THEN
    IF (c->'length'->>'deduction_mm')::NUMERIC < 0 THEN RETURN FALSE; END IF;
    IF (c->'length'->>'axis'='FIXED') <> (c->'length'->>'fixed_mm' IS NOT NULL) THEN RETURN FALSE; END IF;
    IF COALESCE((c->'length'->>'fixed_mm')::NUMERIC,1) <= 0 THEN RETURN FALSE; END IF;
  END IF;
  FOR m IN SELECT value FROM jsonb_array_elements(COALESCE(c->'machining','[]'::JSONB)) LOOP
    IF COALESCE((m->>'depth_mm')::NUMERIC,1)<=0 THEN RETURN FALSE; END IF;
    IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(COALESCE(m->'positions_mm','[]'::JSONB)) p WHERE p::NUMERIC<0) THEN RETURN FALSE; END IF;
    IF (SELECT COUNT(DISTINCT p) FROM jsonb_array_elements_text(COALESCE(m->'positions_mm','[]'::JSONB)) p) <> jsonb_array_length(COALESCE(m->'positions_mm','[]'::JSONB)) THEN RETURN FALSE; END IF;
  END LOOP;
  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN RETURN FALSE;
END; $$;

CREATE FUNCTION public.hardware_class_authority_valid(a JSONB) RETURNS BOOLEAN
LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,extensions AS $$
DECLARE h JSONB; c JSONB; opt JSONB; color JSONB; low NUMERIC; high NUMERIC;
BEGIN
  IF a IS NULL THEN RETURN TRUE; END IF;
  IF NOT public.hardware_schema_valid(a,'__SCHEMA__'::JSONB,'__SCHEMA__'::JSONB) THEN RETURN FALSE; END IF;
  low := (a->>'minimum_width_height_ratio')::NUMERIC;
  high := (a->>'maximum_width_height_ratio')::NUMERIC;
  IF COALESCE(low,1)<=0 OR COALESCE(high,1)<=0 OR low>high OR COALESCE((a->>'minimum_stay_height_mm')::NUMERIC,1)<=0 THEN RETURN FALSE; END IF;
  IF (SELECT COUNT(DISTINCT v->>'sku') FROM jsonb_array_elements(a->'components') v) <> jsonb_array_length(a->'components') THEN RETURN FALSE; END IF;
  IF (SELECT COUNT(DISTINCT v->>'code') FROM jsonb_array_elements(COALESCE(a->'handles','[]'::JSONB)) v) <> jsonb_array_length(COALESCE(a->'handles','[]'::JSONB)) THEN RETURN FALSE; END IF;
  IF (SELECT COUNT(DISTINCT v->>'code') FROM jsonb_array_elements(COALESCE(a->'options','[]'::JSONB)) v) <> jsonb_array_length(COALESCE(a->'options','[]'::JSONB)) THEN RETURN FALSE; END IF;
  FOR c IN SELECT value FROM jsonb_array_elements(a->'components') LOOP
    IF NOT public.hardware_component_rule_valid(c) THEN RETURN FALSE; END IF;
  END LOOP;
  IF jsonb_array_length(COALESCE(a->'handles','[]'::JSONB))=0 AND a->>'default_handle' IS NOT NULL THEN RETURN FALSE; END IF;
  IF jsonb_array_length(COALESCE(a->'handles','[]'::JSONB))>0 AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(a->'handles') v WHERE v->>'code'=a->>'default_handle') THEN RETURN FALSE; END IF;
  FOR h IN SELECT value FROM jsonb_array_elements(COALESCE(a->'handles','[]'::JSONB)) LOOP
    IF (h->>'minimum_from_bottom_mm')::NUMERIC<0 OR (h->>'minimum_from_top_mm')::NUMERIC<0 THEN RETURN FALSE; END IF;
    IF h->>'vertical_rule'<>'CENTER' AND (h->>'default_height_mm' IS NULL OR (h->>'default_height_mm')::NUMERIC<=0) THEN RETURN FALSE; END IF;
    IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(h->'colors') v WHERE v->>'code'=h->>'default_color') THEN RETURN FALSE; END IF;
    IF (SELECT COUNT(DISTINCT v->>'code') FROM jsonb_array_elements(h->'colors') v) <> jsonb_array_length(h->'colors') THEN RETURN FALSE; END IF;
    FOR color IN SELECT value FROM jsonb_array_elements(h->'colors') LOOP
      IF color->'component'->>'category'<>'HANDLE' OR NOT public.hardware_component_rule_valid(color->'component') THEN RETURN FALSE; END IF;
    END LOOP;
  END LOOP;
  FOR opt IN SELECT value FROM jsonb_array_elements(COALESCE(a->'options','[]'::JSONB)) LOOP
    IF opt->>'security_rating' IS NOT NULL AND opt->>'kind'<>'SECURITY' THEN RETURN FALSE; END IF;
    IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(COALESCE(opt->'replaces_skus','[]'::JSONB)) sku WHERE NOT EXISTS(SELECT 1 FROM jsonb_array_elements(a->'components') v WHERE v->>'sku'=sku)) THEN RETURN FALSE; END IF;
    FOR c IN SELECT value FROM jsonb_array_elements(opt->'components') LOOP
      IF NOT public.hardware_component_rule_valid(c) THEN RETURN FALSE; END IF;
    END LOOP;
  END LOOP;
  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN RETURN FALSE;
END; $$;
ALTER TABLE public.hardware_kits ADD CONSTRAINT hardware_class_authority_contract
CHECK (public.hardware_class_authority_valid(class_authority)
       AND (class_authority IS NULL OR contents='[]'::JSONB));
CREATE UNIQUE INDEX hardware_family_priority_unique ON public.hardware_kits
  (system_id,COALESCE(org_id,'00000000-0000-0000-0000-000000000000'::UUID),
   (class_authority->>'family_code'),(class_authority->>'priority'))
  WHERE class_authority IS NOT NULL AND is_active;
COMMENT ON COLUMN public.hardware_kits.class_authority IS
 'D04 optional exact family/class/component authority; NULL preserves historical kit math and sealed bytes.';
COMMIT;
""".replace("__SCHEMA__", schema.replace("'", "''")).replace("__SCHEMA_VALIDATOR__",
    (ROOT / "scripts/hardware_schema.sql").read_text(encoding="utf-8"))


def hardware_sql(records=None, *, version=4) -> str:
    records = hardware_manifest() if records is None else records
    sql = generated_sql(records, version=version).removesuffix("COMMIT;\n")
    sql = sql.replace("scripts/generate_demo_catalog.py", "scripts/generate_demo_hardware.py")
    additions = []
    for record in records:
        code = record["code"]
        system_id = uid(code, version=version)
        for kind in ("SAFE", "LOWE"):
            sku = f"{code}-GLASS-{kind}"
            mapping_id = uid(code, sku, version=version)
            additions.append(insert("glass_purchase_mappings", {"id": mapping_id,
                "org_id": None, "system_id": system_id, "technical_sku": sku,
                "purchasing_sku": sku, "manufacturer_name": "Vidriero sintético · DEMO",
                "purchase_unit": "EA", "version": 1,
                "glass_spec": "3+3 PVB 0,38 / 13,62 aire aluminio / 4 templado" if kind == "SAFE"
                    else "4 / 16 Ar borde cálido / 4 Low-E (c3)", "provenance": {"source": SOURCE}}))
            additions.append(insert("catalog_glass_compositions", {
                "id": uid(code, "composition/"+sku, version=version), "org_id": None,
                "system_id": system_id, "mapping_id": mapping_id, "status": "PARSED",
                "product": demo_glass_product(code, kind).model_dump(mode="json")}))
        for sku, unit, rate in demo_glass_rates(code):
            additions.append(shared_demo_price({"id": uid(code, "price/"+sku, version=version),
                "org_id": None, "system_id": system_id, "sku": sku, "unit": unit,
                "unit_cost": rate, "seed": 20261230, "source": SOURCE, "is_demo": True, "currency": "CLP"}))
    return sql + "\n" + "\n".join(additions) + "\nCOMMIT;\n"


SEED_MARKER = "-- D04 generated documentary seed; see scripts/generate_demo_hardware.py."


def documentary_seed_sql() -> str:
    """Complete the additive policies after seed.sql provides their sources.

    Existing installations already copy these in the migration. An empty
    installation seeds the canonical source later; both paths use the same
    deterministic identities and never rewrite an existing policy.
    """
    codes = ",".join("'" + record["code"] + "'" for record in hardware_manifest())
    eligible = f"s.is_global AND s.is_demo AND s.version=4 AND s.org_id IS NULL AND s.code IN ({codes})"
    statements = [f"""{SEED_MARKER}
DO $d04_seed$ BEGIN
IF EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='hardware_kits'
      AND column_name='class_authority') THEN
    INSERT INTO public.inspector_rule_configs(id,system_id,org_id,rule_id,params)
    SELECT uuid_generate_v5(uuid_ns_url(),
        'https://dekopen.local/catalog/v4/'||s.code||'/inspection/'||r.rule_id),
        s.id,NULL,r.rule_id,r.params
    FROM public.profile_systems s CROSS JOIN public.inspector_rule_configs r
    WHERE {eligible}
      AND r.system_id='3067da09-3119-5ad0-a1d5-498cd2dfd753' AND r.org_id IS NULL
    ON CONFLICT (id) DO NOTHING;
"""]
    for table in ("manufacturing_placement_policies", "handle_requirement_policies"):
        statements.append(f"""
    INSERT INTO public.{table}(id,system_id,org_id,version,authority)
    SELECT uuid_generate_v5(uuid_ns_url(),
        'https://dekopen.local/catalog/v4/'||s.code||'/{table}'),
        s.id,NULL,p.version,jsonb_set(p.authority,'{{policy_id}}',to_jsonb(s.code||'_DEMO_V4'))
    FROM public.profile_systems s CROSS JOIN LATERAL (
        SELECT version,authority FROM public.{table}
        WHERE system_id='3067da09-3119-5ad0-a1d5-498cd2dfd753' AND org_id IS NULL
        ORDER BY version DESC,id LIMIT 1
    ) p
    WHERE {eligible}
    ON CONFLICT (id) DO NOTHING;
""")
    return "\n".join(statements) + "END IF;\nEND $d04_seed$;\n"


if __name__ == "__main__":
    (ROOT / "supabase/migrations/20270101000000_hardware_classes.sql").write_text(schema_sql(), encoding="utf-8", newline="\n")
    (ROOT / "supabase/migrations/20270101000100_demo_hardware_classes.sql").write_text(hardware_sql(), encoding="utf-8", newline="\n")
    seed = ROOT / "supabase/seed.sql"
    historical_seed = seed.read_text(encoding="utf-8").split(SEED_MARKER, 1)[0].rstrip()
    seed.write_text(historical_seed + "\n\n" + documentary_seed_sql(), encoding="utf-8", newline="\n")
    print("D04 schema and additive v4 synthetic authorities reproduced.")
