"""Reproduce D06 schema and additive v6, leaving v1-v5 intact."""

import json
from pathlib import Path
import sys
from uuid import NAMESPACE_URL, uuid5

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "engine/src"))
from pydantic import TypeAdapter  # noqa: E402
from dekopen_engine.extra_models import ExtraAuthority, ExtraPolicy, ExtraSelection  # noqa: E402
from backend.catalogs.demo_extras import extra_manifest, SOURCE  # noqa: E402
from scripts.generate_demo_hardware import hardware_sql  # noqa: E402
from scripts.generate_demo_finishes import finish_seed_sql  # noqa: E402
from scripts.generate_demo_catalog import uid, insert  # noqa: E402

SCHEMA_FILE = ROOT / "supabase/migrations/20270103000000_accessory_services.sql"
DEMO_FILE = ROOT / "supabase/migrations/20270103000100_demo_extra_catalog.sql"
SEED_MARKER = "-- D06 generated documentary seed; see scripts/generate_demo_extras.py."


def schema_sql() -> str:
    text = (ROOT / "scripts/extras_schema.sql").read_text(encoding="utf-8")
    for name, schema in (("AUTHORITY", ExtraAuthority.model_json_schema()), ("POLICY", ExtraPolicy.model_json_schema()),
                         ("SELECTIONS", TypeAdapter(list[ExtraSelection]).json_schema())):
        text = text.replace(f"__{name}_SCHEMA__", json.dumps(schema, sort_keys=True, ensure_ascii=False).replace("'", "''"))
    return "-- Generated by scripts/generate_demo_extras.py. Exact, additive D06 contract.\nBEGIN;\n"+text+"\nCOMMIT;\n"


def extra_sql() -> str:
    records = extra_manifest()
    text = hardware_sql(records, version=6).removesuffix("COMMIT;\n")
    saw = str(uuid5(NAMESPACE_URL, "https://dekopen.local/shot07/cutting/DEMO"))
    additions = []
    for record in records:
        code = record["code"]
        system = uid(code, version=6)
        for key in ("finish_authority", "extra_authority"):
            payload = json.dumps(record["params"][key], ensure_ascii=False).replace("'", "''")
            additions.append(f"UPDATE public.profile_systems SET {key}='{payload}'::JSONB WHERE id='{system}';")
        for binding in record["finish_bindings"]:
            sku, finish = binding["sku"], binding["finish"]
            additions.append(insert("catalog_color_skus", {"id": uid(code, "finish/"+sku+"/"+finish, version=6),
                "org_id": None, "system_id": system, "profile_article_id": uid(code, sku, version=6),
                "finish": finish, "commercial_sku": binding["commercial_sku"],
                "physical_stock_identity": uid(code, "stock/"+sku+"/"+finish, version=6),
                "source": SOURCE, "manufacturer_name": "Fabricante sintético · DEMO", "supplier_name": "Proveedor sintético",
                "stock_color": finish, "cutting_profile_id": saw, "binding_version": 1, "purchase_unit": "BAR", "is_active": True}))
        for definition in record["params"]["extra_authority"]["definitions"]:
            if definition["sku"]:
                additions.append(insert("fitting_purchase_mappings", {"id": uid(code, "extra/"+definition["sku"], version=6),
                    "org_id": None, "system_id": system, "technical_sku": definition["sku"], "purchasing_sku": "COMPRA-"+definition["sku"],
                    "manufacturer_name": "Accesorios a medida · DEMO", "purchase_unit": "EA", "version": 1,
                    "provenance": {"source": SOURCE, "certified": "false", "supply_form": "CUT_TO_SIZE"}}))
    return text+"\n"+"\n".join(additions)+"\nCOMMIT;\n"


def extra_seed_sql() -> str:
    return finish_seed_sql().replace("-- D05 generated documentary seed; see scripts/generate_demo_finishes.py.", SEED_MARKER).replace(
        "d05_seed", "d06_seed").replace("catalog/v5/", "catalog/v6/").replace("s.version=5", "s.version=6").replace("_DEMO_V5", "_DEMO_V6")


if __name__ == "__main__":
    SCHEMA_FILE.write_text(schema_sql(), encoding="utf-8", newline="\n")
    DEMO_FILE.write_text(extra_sql(), encoding="utf-8", newline="\n")
    seed = ROOT / "supabase/seed.sql"
    prior = seed.read_text(encoding="utf-8").split(SEED_MARKER, 1)[0].rstrip()
    seed.write_text(prior+"\n\n"+extra_seed_sql(), encoding="utf-8", newline="\n")
    print("D06 exact schema and additive v6 accessories reproduced.")
