-- The finite vocabulary generated by HardwareClassAuthority is checked by
-- the generator. Cross-field authority is checked by companion validators.
-- This exact validator also runs on PostgreSQL 16 without extensions.
CREATE FUNCTION public.hardware_schema_valid(v JSONB, s JSONB, root JSONB) RETURNS BOOLEAN
LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public AS $$
DECLARE part JSONB; child JSONB; k TEXT; t TEXT; n NUMERIC;
BEGIN
  IF v IS NULL OR s IS NULL THEN RETURN FALSE; END IF;
  IF s ? '$ref' THEN
    RETURN public.hardware_schema_valid(v,root->'$defs'->split_part(s->>'$ref','/',3),root);
  END IF;
  IF s ? 'anyOf' THEN
    FOR part IN SELECT value FROM jsonb_array_elements(s->'anyOf') LOOP
      IF public.hardware_schema_valid(v,part,root) THEN RETURN TRUE; END IF;
    END LOOP;
    RETURN FALSE;
  END IF;
  IF s ? 'const' AND v <> s->'const' THEN RETURN FALSE; END IF;
  IF s ? 'enum' AND NOT (s->'enum' @> ('[' || v::TEXT || ']')::JSONB) THEN RETURN FALSE; END IF;
  t := s->>'type';
  IF t='null' THEN RETURN v='null'::JSONB; END IF;
  IF t IN ('object','array','string','boolean','number') AND jsonb_typeof(v)<>t THEN RETURN FALSE; END IF;
  IF t='integer' THEN
    IF jsonb_typeof(v)<>'number' THEN RETURN FALSE; END IF;
    n := v::TEXT::NUMERIC;
    IF n<>trunc(n) THEN RETURN FALSE; END IF;
  END IF;
  IF t IN ('integer','number') THEN
    n := v::TEXT::NUMERIC;
    IF s ? 'minimum' AND n<(s->>'minimum')::NUMERIC THEN RETURN FALSE; END IF;
    IF s ? 'maximum' AND n>(s->>'maximum')::NUMERIC THEN RETURN FALSE; END IF;
    IF s ? 'exclusiveMinimum' AND n<=(s->>'exclusiveMinimum')::NUMERIC THEN RETURN FALSE; END IF;
    IF s ? 'exclusiveMaximum' AND n>=(s->>'exclusiveMaximum')::NUMERIC THEN RETURN FALSE; END IF;
  ELSIF t='string' THEN
    IF s ? 'minLength' AND length(v#>>'{}')<(s->>'minLength')::INT THEN RETURN FALSE; END IF;
    IF s ? 'maxLength' AND length(v#>>'{}')>(s->>'maxLength')::INT THEN RETURN FALSE; END IF;
    IF s ? 'pattern' AND NOT (v#>>'{}' ~ (s->>'pattern')) THEN RETURN FALSE; END IF;
  ELSIF t='array' THEN
    IF s ? 'minItems' AND jsonb_array_length(v)<(s->>'minItems')::INT THEN RETURN FALSE; END IF;
    IF s ? 'maxItems' AND jsonb_array_length(v)>(s->>'maxItems')::INT THEN RETURN FALSE; END IF;
    FOR child IN SELECT value FROM jsonb_array_elements(v) LOOP
      IF NOT public.hardware_schema_valid(child,s->'items',root) THEN RETURN FALSE; END IF;
    END LOOP;
  ELSIF t='object' THEN
    FOR k IN SELECT jsonb_array_elements_text(COALESCE(s->'required','[]'::JSONB)) LOOP
      IF NOT v ? k THEN RETURN FALSE; END IF;
    END LOOP;
    FOR k,child IN SELECT key,value FROM jsonb_each(v) LOOP
      IF NOT (s->'properties') ? k THEN
        IF s->'additionalProperties'='false'::JSONB THEN RETURN FALSE; END IF;
      ELSIF NOT public.hardware_schema_valid(child,s->'properties'->k,root) THEN RETURN FALSE;
      END IF;
    END LOOP;
  END IF;
  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN RETURN FALSE;
END; $$;
