// Generated from dekopen_engine.symbols; do not edit.
export const symbolTemplates = {
  turn_left: [
    ["0.2", "0.2"],
    ["0.8", "0.5"],
    ["0.2", "0.8"],
  ],
  turn_right: [
    ["0.8", "0.2"],
    ["0.2", "0.5"],
    ["0.8", "0.8"],
  ],
  tilt: [
    ["0.2", "0.8"],
    ["0.5", "0.2"],
    ["0.8", "0.8"],
  ],
  awning: [
    ["0.2", "0.2"],
    ["0.5", "0.8"],
    ["0.8", "0.2"],
  ],
  slide_right: [
    ["0.25", "0.5"],
    ["0.75", "0.5"],
  ],
  slide_right_head: [
    ["0.65", "0.44"],
    ["0.75", "0.5"],
    ["0.65", "0.56"],
  ],
  slide_left: [
    ["0.75", "0.5"],
    ["0.25", "0.5"],
  ],
  slide_left_head: [
    ["0.35", "0.44"],
    ["0.25", "0.5"],
    ["0.35", "0.56"],
  ],
  lift: [
    ["0.5", "0.7"],
    ["0.5", "0.6"],
  ],
  parallel: [
    ["0.3", "0.65"],
    ["0.5", "0.7"],
    ["0.7", "0.65"],
  ],
  fold: [
    ["0.2", "0.2"],
    ["0.4", "0.8"],
    ["0.6", "0.2"],
    ["0.8", "0.8"],
  ],
  pivot_v: [
    ["0.5", "0.2"],
    ["0.5", "0.8"],
  ],
  pivot_h: [
    ["0.2", "0.5"],
    ["0.8", "0.5"],
  ],
  vertical_slide: [
    ["0.5", "0.75"],
    ["0.5", "0.25"],
  ],
  vertical_slide_head: [
    ["0.44", "0.35"],
    ["0.5", "0.25"],
    ["0.56", "0.35"],
  ],
} as const;
export const symbolMotions: Record<string, readonly (keyof typeof symbolTemplates)[]> = {
  "FIXED/LEFT/": [],
  "FIXED/LEFT/LEFT": [],
  "FIXED/LEFT/RIGHT": [],
  "FIXED/RIGHT/": [],
  "FIXED/RIGHT/LEFT": [],
  "FIXED/RIGHT/RIGHT": [],
  "FIXED/NONE/": [],
  "FIXED/NONE/LEFT": [],
  "FIXED/NONE/RIGHT": [],
  "TURN/LEFT/": ["turn_left"],
  "TURN/LEFT/LEFT": ["turn_left"],
  "TURN/LEFT/RIGHT": ["turn_left"],
  "TURN/RIGHT/": ["turn_right"],
  "TURN/RIGHT/LEFT": ["turn_right"],
  "TURN/RIGHT/RIGHT": ["turn_right"],
  "TURN/NONE/": [],
  "TURN/NONE/LEFT": [],
  "TURN/NONE/RIGHT": [],
  "TILT/LEFT/": ["tilt"],
  "TILT/LEFT/LEFT": ["tilt"],
  "TILT/LEFT/RIGHT": ["tilt"],
  "TILT/RIGHT/": ["tilt"],
  "TILT/RIGHT/LEFT": ["tilt"],
  "TILT/RIGHT/RIGHT": ["tilt"],
  "TILT/NONE/": ["tilt"],
  "TILT/NONE/LEFT": ["tilt"],
  "TILT/NONE/RIGHT": ["tilt"],
  "TILT_TURN/LEFT/": ["turn_left", "tilt"],
  "TILT_TURN/LEFT/LEFT": ["turn_left", "tilt"],
  "TILT_TURN/LEFT/RIGHT": ["turn_left", "tilt"],
  "TILT_TURN/RIGHT/": ["turn_right", "tilt"],
  "TILT_TURN/RIGHT/LEFT": ["turn_right", "tilt"],
  "TILT_TURN/RIGHT/RIGHT": ["turn_right", "tilt"],
  "TILT_TURN/NONE/": ["tilt"],
  "TILT_TURN/NONE/LEFT": ["tilt"],
  "TILT_TURN/NONE/RIGHT": ["tilt"],
  "TOP_HUNG/LEFT/": ["awning"],
  "TOP_HUNG/LEFT/LEFT": ["awning"],
  "TOP_HUNG/LEFT/RIGHT": ["awning"],
  "TOP_HUNG/RIGHT/": ["awning"],
  "TOP_HUNG/RIGHT/LEFT": ["awning"],
  "TOP_HUNG/RIGHT/RIGHT": ["awning"],
  "TOP_HUNG/NONE/": ["awning"],
  "TOP_HUNG/NONE/LEFT": ["awning"],
  "TOP_HUNG/NONE/RIGHT": ["awning"],
  "BOTTOM_HUNG/LEFT/": ["tilt"],
  "BOTTOM_HUNG/LEFT/LEFT": ["tilt"],
  "BOTTOM_HUNG/LEFT/RIGHT": ["tilt"],
  "BOTTOM_HUNG/RIGHT/": ["tilt"],
  "BOTTOM_HUNG/RIGHT/LEFT": ["tilt"],
  "BOTTOM_HUNG/RIGHT/RIGHT": ["tilt"],
  "BOTTOM_HUNG/NONE/": ["tilt"],
  "BOTTOM_HUNG/NONE/LEFT": ["tilt"],
  "BOTTOM_HUNG/NONE/RIGHT": ["tilt"],
  "SLIDE/LEFT/": [],
  "SLIDE/LEFT/LEFT": ["slide_left", "slide_left_head"],
  "SLIDE/LEFT/RIGHT": ["slide_right", "slide_right_head"],
  "SLIDE/RIGHT/": [],
  "SLIDE/RIGHT/LEFT": ["slide_left", "slide_left_head"],
  "SLIDE/RIGHT/RIGHT": ["slide_right", "slide_right_head"],
  "SLIDE/NONE/": [],
  "SLIDE/NONE/LEFT": ["slide_left", "slide_left_head"],
  "SLIDE/NONE/RIGHT": ["slide_right", "slide_right_head"],
  "LIFT_SLIDE/LEFT/": ["lift"],
  "LIFT_SLIDE/LEFT/LEFT": ["slide_left", "slide_left_head", "lift"],
  "LIFT_SLIDE/LEFT/RIGHT": ["slide_right", "slide_right_head", "lift"],
  "LIFT_SLIDE/RIGHT/": ["lift"],
  "LIFT_SLIDE/RIGHT/LEFT": ["slide_left", "slide_left_head", "lift"],
  "LIFT_SLIDE/RIGHT/RIGHT": ["slide_right", "slide_right_head", "lift"],
  "LIFT_SLIDE/NONE/": ["lift"],
  "LIFT_SLIDE/NONE/LEFT": ["slide_left", "slide_left_head", "lift"],
  "LIFT_SLIDE/NONE/RIGHT": ["slide_right", "slide_right_head", "lift"],
  "PARALLEL_SLIDE/LEFT/": ["parallel"],
  "PARALLEL_SLIDE/LEFT/LEFT": ["slide_left", "slide_left_head", "parallel"],
  "PARALLEL_SLIDE/LEFT/RIGHT": ["slide_right", "slide_right_head", "parallel"],
  "PARALLEL_SLIDE/RIGHT/": ["parallel"],
  "PARALLEL_SLIDE/RIGHT/LEFT": ["slide_left", "slide_left_head", "parallel"],
  "PARALLEL_SLIDE/RIGHT/RIGHT": ["slide_right", "slide_right_head", "parallel"],
  "PARALLEL_SLIDE/NONE/": ["parallel"],
  "PARALLEL_SLIDE/NONE/LEFT": ["slide_left", "slide_left_head", "parallel"],
  "PARALLEL_SLIDE/NONE/RIGHT": ["slide_right", "slide_right_head", "parallel"],
  "FOLD/LEFT/": ["fold"],
  "FOLD/LEFT/LEFT": ["fold"],
  "FOLD/LEFT/RIGHT": ["fold"],
  "FOLD/RIGHT/": ["fold"],
  "FOLD/RIGHT/LEFT": ["fold"],
  "FOLD/RIGHT/RIGHT": ["fold"],
  "FOLD/NONE/": ["fold"],
  "FOLD/NONE/LEFT": ["fold"],
  "FOLD/NONE/RIGHT": ["fold"],
  "PIVOT_V/LEFT/": ["pivot_v"],
  "PIVOT_V/LEFT/LEFT": ["pivot_v"],
  "PIVOT_V/LEFT/RIGHT": ["pivot_v"],
  "PIVOT_V/RIGHT/": ["pivot_v"],
  "PIVOT_V/RIGHT/LEFT": ["pivot_v"],
  "PIVOT_V/RIGHT/RIGHT": ["pivot_v"],
  "PIVOT_V/NONE/": ["pivot_v"],
  "PIVOT_V/NONE/LEFT": ["pivot_v"],
  "PIVOT_V/NONE/RIGHT": ["pivot_v"],
  "PIVOT_H/LEFT/": ["pivot_h"],
  "PIVOT_H/LEFT/LEFT": ["pivot_h"],
  "PIVOT_H/LEFT/RIGHT": ["pivot_h"],
  "PIVOT_H/RIGHT/": ["pivot_h"],
  "PIVOT_H/RIGHT/LEFT": ["pivot_h"],
  "PIVOT_H/RIGHT/RIGHT": ["pivot_h"],
  "PIVOT_H/NONE/": ["pivot_h"],
  "PIVOT_H/NONE/LEFT": ["pivot_h"],
  "PIVOT_H/NONE/RIGHT": ["pivot_h"],
  "VERTICAL_SLIDE/LEFT/": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/LEFT/LEFT": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/LEFT/RIGHT": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/RIGHT/": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/RIGHT/LEFT": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/RIGHT/RIGHT": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/NONE/": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/NONE/LEFT": ["vertical_slide", "vertical_slide_head"],
  "VERTICAL_SLIDE/NONE/RIGHT": ["vertical_slide", "vertical_slide_head"],
};
