from django.urls import path

from production.views import (
    ProductionOrderDeliveryConfirmationView,
    ProductionOrderDeliveryConfirmView,
    ProductionOrderDeliveryTransitionView,
    ProductionOrderDeliveryView,
    ProductionOrderCncExportView,
    ProductionOrderDispatchView,
    ProductionOrderDxfExportView,
    ProductionOrderDxfFileView,
    ProductionOrderOpsExportView,
    ProductionOrderOpsFileView,
    ProductionOrderDispatchNoteView,
    ProductionOrderDispatchNoteDteView,
    ProductionOrderInstallationView,
    ProductionOrderLabelsView,
    ProductionOrderCncFileView,
    ProductionOrderDetailView,
    ProductionOrderListView,
    ProductionOrderOptimizeView,
    ProductionOrderPackingView,
    ProductionPrepView,
    ProductionOrderTraceView,
    ProductionPieceTraceView,
    ProductionVersionTraceView,
    ProductionOrderRemakeView,
    ProductionReleaseView,
    ProductionStepTransitionView,
    WorkCenterListView,
)

urlpatterns = [
    path("prep/", ProductionPrepView.as_view(), name="production-prep"),
    path("orders/", ProductionOrderListView.as_view(), name="production-orders"),
    path(
        "orders/<uuid:order_id>/trace/",
        ProductionOrderTraceView.as_view(),
        name="production-order-trace",
    ),
    path(
        "pieces/<str:piece_id>/trace/",
        ProductionPieceTraceView.as_view(),
        name="production-piece-trace",
    ),
    path(
        "orders/<uuid:order_id>/",
        ProductionOrderDetailView.as_view(),
        name="production-order-detail",
    ),
    path(
        "orders/<uuid:order_id>/optimize/",
        ProductionOrderOptimizeView.as_view(),
        name="production-order-optimize",
    ),
    path(
        "orders/<uuid:order_id>/cnc-export/",
        ProductionOrderCncExportView.as_view(),
        name="production-order-cnc-export",
    ),
    path(
        "orders/<uuid:order_id>/cnc-export/<str:filename>",
        ProductionOrderCncFileView.as_view(),
        name="production-order-cnc-file",
    ),
    path(
        "orders/<uuid:order_id>/dxf-export/",
        ProductionOrderDxfExportView.as_view(),
        name="production-order-dxf-export",
    ),
    path(
        "orders/<uuid:order_id>/dxf-export/<str:filename>",
        ProductionOrderDxfFileView.as_view(),
        name="production-order-dxf-file",
    ),
    path(
        "orders/<uuid:order_id>/operations-export/",
        ProductionOrderOpsExportView.as_view(),
        name="production-order-ops-export",
    ),
    path(
        "orders/<uuid:order_id>/operations-export/<str:filename>",
        ProductionOrderOpsFileView.as_view(),
        name="production-order-ops-file",
    ),
    path(
        "orders/<uuid:order_id>/packing/",
        ProductionOrderPackingView.as_view(),
        name="production-order-packing",
    ),
    path(
        "orders/<uuid:order_id>/labels/",
        ProductionOrderLabelsView.as_view(),
        name="production-order-labels",
    ),
    path(
        "orders/<uuid:order_id>/delivery/",
        ProductionOrderDeliveryView.as_view(),
        name="production-order-delivery",
    ),
    path(
        "orders/<uuid:order_id>/delivery/transition/",
        ProductionOrderDeliveryTransitionView.as_view(),
        name="production-order-delivery-transition",
    ),
    path(
        "orders/<uuid:order_id>/delivery/confirm/",
        ProductionOrderDeliveryConfirmView.as_view(),
        name="production-order-delivery-confirm",
    ),
    path(
        "orders/<uuid:order_id>/delivery/confirmation/",
        ProductionOrderDeliveryConfirmationView.as_view(),
        name="production-order-delivery-confirmation",
    ),
    path(
        "orders/<uuid:order_id>/dispatch/",
        ProductionOrderDispatchView.as_view(),
        name="production-order-dispatch",
    ),
    path(
        "orders/<uuid:order_id>/dispatch-note/",
        ProductionOrderDispatchNoteView.as_view(),
        name="production-order-dispatch-note",
    ),
    path(
        "orders/<uuid:order_id>/dispatch-note-dte/",
        ProductionOrderDispatchNoteDteView.as_view(),
        name="production-order-dispatch-note-dte",
    ),
    path(
        "orders/<uuid:order_id>/install/",
        ProductionOrderInstallationView.as_view(),
        name="production-order-install",
    ),
    path(
        "orders/<uuid:order_id>/remake/",
        ProductionOrderRemakeView.as_view(),
        name="production-order-remake",
    ),
    path(
        "steps/<uuid:step_id>/transition/",
        ProductionStepTransitionView.as_view(),
        name="production-step-transition",
    ),
    path(
        "versions/<uuid:version_id>/trace/",
        ProductionVersionTraceView.as_view(),
        name="production-version-trace",
    ),
    path(
        "versions/<uuid:version_id>/release/",
        ProductionReleaseView.as_view(),
        name="production-release",
    ),
    path("work-centers/", WorkCenterListView.as_view(), name="production-work-centers"),
]
