from django.urls import path

from production.views import (
    ProductionOrderDeliveryConfirmationView,
    ProductionOrderDeliveryConfirmView,
    ProductionOrderDeliveryTransitionView,
    ProductionOrderDeliveryView,
    ProductionOrderCncExportView,
    ProductionOrderDispatchView,
    ProductionOrderDispatchNoteView,
    ProductionOrderInstallationView,
    ProductionOrderLabelsView,
    ProductionOrderCncFileView,
    ProductionOrderDetailView,
    ProductionOrderListView,
    ProductionOrderOptimizeView,
    ProductionOrderPackingView,
    ProductionOrderRemakeView,
    ProductionReleaseView,
    ProductionStepTransitionView,
    WorkCenterListView,
)

urlpatterns = [
    path("orders/", ProductionOrderListView.as_view(), name="production-orders"),
    path(
        "orders/<uuid:order_id>/",
        ProductionOrderDetailView.as_view(),
        name="production-order-detail",
    ),
    path(
        "orders/<uuid:order_id>/optimize/",
        ProductionOrderOptimizeView.as_view(),
        name="production-order-optimize",
    ),
    path(
        "orders/<uuid:order_id>/cnc-export/",
        ProductionOrderCncExportView.as_view(),
        name="production-order-cnc-export",
    ),
    path(
        "orders/<uuid:order_id>/cnc-export/<str:filename>",
        ProductionOrderCncFileView.as_view(),
        name="production-order-cnc-file",
    ),
    path(
        "orders/<uuid:order_id>/packing/",
        ProductionOrderPackingView.as_view(),
        name="production-order-packing",
    ),
    path(
        "orders/<uuid:order_id>/labels/",
        ProductionOrderLabelsView.as_view(),
        name="production-order-labels",
    ),
    path(
        "orders/<uuid:order_id>/delivery/",
        ProductionOrderDeliveryView.as_view(),
        name="production-order-delivery",
    ),
    path(
        "orders/<uuid:order_id>/delivery/transition/",
        ProductionOrderDeliveryTransitionView.as_view(),
        name="production-order-delivery-transition",
    ),
    path(
        "orders/<uuid:order_id>/delivery/confirm/",
        ProductionOrderDeliveryConfirmView.as_view(),
        name="production-order-delivery-confirm",
    ),
    path(
        "orders/<uuid:order_id>/delivery/confirmation/",
        ProductionOrderDeliveryConfirmationView.as_view(),
        name="production-order-delivery-confirmation",
    ),
    path(
        "orders/<uuid:order_id>/dispatch/",
        ProductionOrderDispatchView.as_view(),
        name="production-order-dispatch",
    ),
    path(
        "orders/<uuid:order_id>/dispatch-note/",
        ProductionOrderDispatchNoteView.as_view(),
        name="production-order-dispatch-note",
    ),
    path(
        "orders/<uuid:order_id>/install/",
        ProductionOrderInstallationView.as_view(),
        name="production-order-install",
    ),
    path(
        "orders/<uuid:order_id>/remake/",
        ProductionOrderRemakeView.as_view(),
        name="production-order-remake",
    ),
    path(
        "steps/<uuid:step_id>/transition/",
        ProductionStepTransitionView.as_view(),
        name="production-step-transition",
    ),
    path(
        "versions/<uuid:version_id>/release/",
        ProductionReleaseView.as_view(),
        name="production-release",
    ),
    path("work-centers/", WorkCenterListView.as_view(), name="production-work-centers"),
]
