BEGIN;

-- A mutable, unpriced draft may change catalog identity. Issued/revision and
-- commercial snapshots remain pinned to their immutable authority. Historical
-- family copies keep the original manufacturing values; v2 fixtures are only
-- selected for new work. No engine output is regenerated by SQL.
CREATE TABLE public.catalog_family_migrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES public.tenancy_organizations(id) ON DELETE CASCADE,
    position_id UUID NOT NULL,
    old_system_id UUID NOT NULL,
    new_system_id UUID,
    outcome TEXT NOT NULL CHECK(outcome IN ('MIGRATED','PRESERVED_COMMERCIAL','PRESERVED_ISSUED','MIXED_FAMILIES')),
    reason TEXT NOT NULL,
    previous_bom JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(position_id)
);
ALTER TABLE public.catalog_family_migrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY catalog_family_migrations_read ON public.catalog_family_migrations FOR SELECT TO authenticated
    USING(private.pricing_role(org_id,ARRAY['OWNER','ESTIMATOR','WORKSHOP_MANAGER']));
REVOKE ALL ON public.catalog_family_migrations FROM anon,authenticated;
GRANT SELECT ON public.catalog_family_migrations TO authenticated;
GRANT ALL ON public.catalog_family_migrations TO service_role;
CREATE TRIGGER immutable_evidence BEFORE UPDATE OR DELETE ON public.catalog_family_migrations
    FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_evidence();

CREATE FUNCTION private.catalog_json_bytes(value JSONB) RETURNS TEXT
LANGUAGE plpgsql IMMUTABLE SET search_path='' AS $$
DECLARE result TEXT;
BEGIN
    IF jsonb_typeof(value)='object' THEN
        SELECT '{' || coalesce(string_agg(to_jsonb(key)::TEXT || ':' || private.catalog_json_bytes(item), ',' ORDER BY key COLLATE "C"),'') || '}'
        INTO result FROM jsonb_each(value) AS pair(key,item);
        RETURN result;
    ELSIF jsonb_typeof(value)='array' THEN
        SELECT '[' || coalesce(string_agg(private.catalog_json_bytes(item),',' ORDER BY ordinal),'') || ']'
        INTO result FROM jsonb_array_elements(value) WITH ORDINALITY AS pair(item,ordinal);
        RETURN result;
    END IF;
    RETURN value::TEXT;
END $$;
REVOKE ALL ON FUNCTION private.catalog_json_bytes(JSONB) FROM PUBLIC;

CREATE FUNCTION private.catalog_saved_families() RETURNS VOID
LANGUAGE plpgsql SET search_path=public,extensions,pg_temp AS $$
DECLARE position RECORD; source RECORD; item RECORD; family TEXT; openings TEXT[];
    target UUID; table_name TEXT; payload JSONB; foreign_key TEXT; bom JSONB;
    old_id UUID; new_id UUID; digest_value TEXT;
    namespace CONSTANT UUID := 'df168df1-7f3e-4e41-a244-a77dfe5ff101';
BEGIN
    IF session_user NOT IN ('postgres','supabase_admin') OR current_setting('role') NOT IN ('none','postgres') THEN
        RAISE EXCEPTION 'catalog_upgrade_platform_only' USING ERRCODE='42501';
    END IF;
    CREATE TEMP TABLE d01_id_map(old_id UUID,new_id UUID,PRIMARY KEY(old_id)) ON COMMIT DROP;
    FOR position IN SELECT p.* FROM public.project_positions p JOIN public.profile_systems s ON s.id=p.system_id
        WHERE s.code='DEMO_60' AND s.system_family IS NULL AND s.is_demo
          AND NOT EXISTS(SELECT 1 FROM public.catalog_family_migrations m WHERE m.position_id=p.id)
        ORDER BY p.id FOR UPDATE OF p
    LOOP
        IF EXISTS(SELECT 1 FROM public.project_versions v WHERE v.project_id=position.project_id)
            OR NOT EXISTS(SELECT 1 FROM public.projects p WHERE p.id=position.project_id AND p.status='DRAFT') THEN
            INSERT INTO public.catalog_family_migrations(org_id,position_id,old_system_id,outcome,reason,previous_bom)
            VALUES(position.org_id,position.id,position.system_id,'PRESERVED_ISSUED',
                'Revisión emitida: conserva catálogo, cortes, documentos y procedencia originales.',position.bom_snapshot);
            CONTINUE;
        END IF;
        IF private.project_has_applied_commercial_state(position.project_id) THEN
            INSERT INTO public.catalog_family_migrations(org_id,position_id,old_system_id,outcome,reason,previous_bom)
            VALUES(position.org_id,position.id,position.system_id,'PRESERVED_COMMERCIAL',
                'Precio aplicado: conserva su autoridad. Restablece los precios y elige la nueva serie para editar.',position.bom_snapshot);
            CONTINUE;
        END IF;
        SELECT array_agg(DISTINCT value #>> '{}') INTO openings FROM jsonb_path_query(position.parametric_tree,'$.**.opening_type') AS entry(value);
        IF EXISTS(SELECT 1 FROM unnest(openings) opening WHERE opening LIKE 'SLIDING%') THEN
            family := 'SLIDING';
            IF EXISTS(SELECT 1 FROM unnest(openings) opening WHERE opening NOT LIKE 'SLIDING%' AND opening<>'FIXED') THEN family:=NULL; END IF;
        ELSIF EXISTS(SELECT 1 FROM unnest(openings) opening WHERE opening LIKE 'DOOR%') THEN
            family := 'DOOR';
            IF EXISTS(SELECT 1 FROM unnest(openings) opening WHERE opening NOT LIKE 'DOOR%' AND opening<>'FIXED') THEN family:=NULL; END IF;
        ELSE family := 'CASEMENT'; END IF;
        IF family IS NULL THEN
            INSERT INTO public.catalog_family_migrations(org_id,position_id,old_system_id,outcome,reason,previous_bom)
            VALUES(position.org_id,position.id,position.system_id,'MIXED_FAMILIES',
                'El conjunto histórico mezcla familias. Sepáralo en productos compatibles para cambiar su catálogo.',position.bom_snapshot);
            CONTINUE;
        END IF;
        target := uuid_generate_v5(namespace,position.system_id::TEXT || ':' || family);
        IF NOT EXISTS(SELECT 1 FROM public.profile_systems s WHERE s.id=target) THEN
            SELECT * INTO source FROM public.profile_systems WHERE id=position.system_id;
            payload := to_jsonb(source) || jsonb_build_object('id',target,'system_family',family,
                'code',CASE family WHEN 'SLIDING' THEN 'DEMO_CORREDERA_60_HIST' WHEN 'DOOR' THEN 'DEMO_PUERTA_60_HIST' ELSE 'DEMO_60_HIST' END,
                'name',CASE family WHEN 'SLIDING' THEN 'PVC corredera 60 mm · DEMO · autoridad guardada'
                    WHEN 'DOOR' THEN 'PVC puerta 60 mm · DEMO · autoridad guardada'
                    ELSE 'PVC practicable 60 mm · DEMO · autoridad guardada' END,
                'technical_locked',FALSE,'legacy_authority',TRUE);
            INSERT INTO public.profile_systems SELECT (jsonb_populate_record(NULL::public.profile_systems,payload)).*;
            TRUNCATE d01_id_map;
            FOREACH table_name IN ARRAY ARRAY['profile_articles','hardware_kits','infill_articles'] LOOP
                FOR item IN EXECUTE format('SELECT to_jsonb(t) AS payload FROM public.%I t WHERE system_id=$1',table_name) USING position.system_id LOOP
                    old_id := (item.payload->>'id')::UUID;
                    new_id := uuid_generate_v5(namespace,target::TEXT || ':' || old_id::TEXT);
                    INSERT INTO d01_id_map VALUES(old_id,new_id);
                    payload := item.payload || jsonb_build_object('id',new_id,'system_id',target);
                    EXECUTE format('INSERT INTO public.%I SELECT (jsonb_populate_record(NULL::public.%I,$1)).*',table_name,table_name) USING payload;
                END LOOP;
            END LOOP;
            FOREACH table_name IN ARRAY ARRAY['glazing_bead_matrix','reinforcement_articles','inspector_rule_configs',
                'manufacturing_placement_policies','handle_requirement_policies','reinforcement_cut_policies','glass_purchase_mappings',
                'fitting_purchase_mappings','profile_purchase_mappings','hardware_purchase_mappings','panel_purchase_authorities'] LOOP
                FOR item IN EXECUTE format('SELECT to_jsonb(t) AS payload FROM public.%I t WHERE '
                    || CASE table_name WHEN 'profile_purchase_mappings' THEN 'profile_article_id IN (SELECT old_id FROM d01_id_map)'
                        WHEN 'hardware_purchase_mappings' THEN 'hardware_kit_id IN (SELECT old_id FROM d01_id_map)'
                        WHEN 'panel_purchase_authorities' THEN 'infill_article_id IN (SELECT old_id FROM d01_id_map)'
                        ELSE 'system_id=$1' END,table_name) USING position.system_id LOOP
                    payload := item.payload;
                    old_id := (payload->>'id')::UUID;
                    new_id := uuid_generate_v5(namespace,target::TEXT || ':' || old_id::TEXT);
                    INSERT INTO d01_id_map VALUES(old_id,new_id) ON CONFLICT DO NOTHING;
                    payload := payload || jsonb_build_object('id',new_id);
                    IF payload ? 'system_id' THEN payload:=payload || jsonb_build_object('system_id',target); END IF;
                    FOREACH foreign_key IN ARRAY ARRAY['bead_article_id','parent_profile_article_id','profile_article_id','hardware_kit_id','infill_article_id'] LOOP
                        IF payload ? foreign_key THEN
                            SELECT m.new_id INTO new_id FROM d01_id_map m WHERE m.old_id=(payload->>foreign_key)::UUID;
                            IF new_id IS NOT NULL THEN payload:=payload || jsonb_build_object(foreign_key,new_id); END IF;
                        END IF;
                    END LOOP;
                    EXECUTE format('INSERT INTO public.%I SELECT (jsonb_populate_record(NULL::public.%I,$1)).*',table_name,table_name) USING payload;
                END LOOP;
            END LOOP;
        END IF;
        bom := position.bom_snapshot;
        IF bom ? 'calculation_hash' THEN
            digest_value := 'sha256:' || encode(digest(convert_to(private.catalog_json_bytes(jsonb_build_object(
                'request',jsonb_build_object('system_id',target::TEXT,'nominal_width_mm',position.width_mm::TEXT,
                    'nominal_height_mm',position.height_mm::TEXT,'color',position.color_interior,'parametric_tree',position.parametric_tree),
                'response_without_calculation_hash',bom-'calculation_hash')),'UTF8'),'sha256'),'hex');
            bom := jsonb_set(bom,'{calculation_hash}',to_jsonb(digest_value));
        END IF;
        UPDATE public.project_positions SET system_id=target,bom_snapshot=bom WHERE id=position.id;
        UPDATE public.position_documentary_inputs SET
            manufacturing_placement_policy_id=uuid_generate_v5(namespace,target::TEXT || ':' || manufacturing_placement_policy_id::TEXT),
            handle_requirement_policy_id=uuid_generate_v5(namespace,target::TEXT || ':' || handle_requirement_policy_id::TEXT),
            reinforcement_cut_policy_id=uuid_generate_v5(namespace,target::TEXT || ':' || reinforcement_cut_policy_id::TEXT)
            ,calculation_hash=CASE WHEN bom ? 'calculation_hash' THEN bom->>'calculation_hash' ELSE calculation_hash END
            WHERE position_id=position.id;
        INSERT INTO public.catalog_family_migrations(org_id,position_id,old_system_id,new_system_id,outcome,reason,previous_bom)
        VALUES(position.org_id,position.id,position.system_id,target,'MIGRATED',
            'Borrador trasladado a su familia con autoridades y números históricos exactos.',position.bom_snapshot);
    END LOOP;
END $$;
REVOKE ALL ON FUNCTION private.catalog_saved_families() FROM PUBLIC;
SELECT private.catalog_saved_families();
DROP FUNCTION private.catalog_saved_families();
DROP FUNCTION private.catalog_json_bytes(JSONB);

COMMIT;
